pipeline {
    agent any

    // Environment variables available to all stages
    environment {
        POM_PATH      = "pom.xml"
        REGISTRY_PATH = "data/cve-registry.json"
        JAR_PATH      = "target/depshield-1.0-SNAPSHOT.jar"
    }

    stages {

        // Stage 1: Get the code
        stage('Checkout') {
            steps {
                echo '------------------------------------------'
                echo ' DepShield Pipeline Starting'
                echo '------------------------------------------'
                checkout scm
            }
        }

        // Stage 2: Compile the project
        stage('Build') {
            steps {
                echo '[Stage 2/5] Building DepShield...'
                sh 'mvn clean package -DskipTests'
                echo 'Build complete.'
            }
        }

        // Stage 3: Run unit tests
        stage('Test') {
            steps {
                echo '[Stage 3/5] Running unit tests...'
                sh 'mvn test'
            }
            post {
                always {
                    // Publish JUnit test results to Jenkins dashboard
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        // Stage 4: Run DepShield vulnerability scan
        stage('Dependency Scan') {
            steps {
                echo '[Stage 4/5] Running DepShield vulnerability scan...'
                sh """
                    java -jar ${JAR_PATH} ${POM_PATH} ${REGISTRY_PATH}
                """
            }
        }

        // Stage 5: Quality Gate — enforce policy
        stage('Quality Gate') {
            steps {
                echo '[Stage 5/5] Evaluating quality gate...'
                script {
                    // Read the audit log generated by DepShield
                    def auditLog = readFile('depshield-audit.log')

                    if (auditLog.contains('BUILD BLOCKED')) {
                        error('Quality Gate FAILED: Critical vulnerabilities detected. Deployment blocked.')
                    } else {
                        echo 'Quality Gate PASSED. Safe to deploy.'
                    }
                }
            }
        }
    }

    // Post-pipeline actions
    post {
        success {
            echo '----------------------------------------------'
            echo ' Pipeline PASSED. No critical vulnerabilities.'
            echo '----------------------------------------------'
        }
        failure {
            echo '---------------------------------------------'
            echo ' Pipeline FAILED. Review DepShield audit log.'
            echo '---------------------------------------------'
        }
        always {
            // Archive the audit log as a build artifact
            archiveArtifacts artifacts: 'depshield-audit.log', 
                             allowEmptyArchive: true
        }
    }
}
